services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=mongodb://mongo:27017
      - MONGO_DB_NAME=shortener
      - PORT=3000
      - EXPIRATION_TIME=5
    depends_on:
      - mongo

  mongo:
    image: mongo:4.2
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
