version: '3.1'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - MONGO_URL=mongodb://mongo:27017/jusfy_shortener
      - PORT=8080
      - EXPIRATION_TIME=5
    depends_on:
      - mongo

  mongo:
    image: mongo:4.2
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
