name: Eslint and Tests

on:
  push:
    branches:
      - main
      - develop
      - feat/**
  pull_request:
    branches:
      - main
      - develop

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install Dependencies
        run: npm ci

      - name: Run ESLint
        run: npx eslint .

      - name: Run Tests
        run: npm run test
