name: Deploy to Staging

on:
  pull_request:
    types: [closed]
    branches: [release]

jobs:
  build-and-push:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3.4.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get latest tag
        id: vars
        run:
          echo "tag=$(git describe --tags --abbrev=0)" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            gabrielpb88/url-shortner:staging-${{ steps.vars.outputs.tag }}
            gabrielpb88/url-shortner:staging
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Deploy to Render
        uses: render/deploy-action@v1
        with:
          apiKey: ${{ secrets.RENDER_STAGING_API_KEY }}
          serviceId: ${{ secrets.RENDER_STAGING_SERVICE_ID }}
          environment: staging
